---
# tasks file for spacewal
#
- name: set activation key for 6
  set_fact:
    spacewalk_activationkey: "{{ spacewalk_activationkey_6 }}"
  when: ansible_distribution_major_version == "6"
- name: set activation key for 7
  set_fact:
    spacewalk_activationkey: "{{ spacewalk_activationkey_7 }}"
  when: ansible_distribution_major_version == "7"
- name: check for Spacewalk server SSL certificate
  stat: path="{{ spacewalk_ssl_path }}"
  register: ssl_file
- name: install Spacewalk SSL rpm
  shell: rpm -ivh http://{{ spacewalk_proxy }}/pub/{{ spacewalk_ssl_package }}
  when: ssl_file.stat.exists == false
- name: register with Spacewalk
  shell: rhnreg_ks --serverUrl=https://{{ spacewalk_proxy }}/XMLRPC --sslCACert={{ spacewalk_ssl_path }} --activationkey={{ spacewalk_activationkey }} --force && touch /etc/sysconfig/rhn/system_registered
  args:
    creates: /etc/sysconfig/rhn/system_registered 
- name: enable rhnsd service
  service: name=rhnsd state=started enabled=true
