class esbu::squid::server (
  $hosts_file = false,
  $ssl_ports = "443",
  $safe_ports = [ "80", "443" ],
  $allowed_networks = [ "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16" ],
  $http_port = "8080",
  $allow_all = false,
  $allow_ftp = false,
  $cache_peer_options = undef,
  $define_cacheobject = true,
  $never_direct_all = false,
  $allowed_sites,
  $log_to_file = true,
  $log_to_syslog = false,
  $dns_nameservers = undef,
) {
  class {'squid':
    config_template       => 'esbu/squid/squid.conf.erb',
    allowed_sites_content => template('esbu/squid/allowed.sites.conf.erb'),
    ssl_ports             => $ssl_ports,
    safe_ports            => $safe_ports,
    allowed_networks      => $allowed_networks,
    http_port             => $http_port,
    allow_all             => $allow_all,
    allow_ftp             => $allow_ftp,
    define_cacheobject    => $define_cacheobject,
    cache_peer_options    => $cache_peer_options,
    never_direct_all      => $never_direct_all,
    log_to_file           => $log_to_file,
    log_to_syslog         => $log_to_syslog,
    dns_nameservers       => $dns_nameservers,
  }
}
