---
# Name: njeji-dcs-mp3.yml
# Author: lbernauer
# Usage: This playbook is used upgrade the Symantec DCS agent to MP3 version on NJeJI vms.
# This playbook includes parts written previously by charris and gwaugh from other playbooks, such as the prepare and reboot functions
# also you may need to add the following directive to your ansible.cfg file in the defaults section
# [defaults]
# allow_world_readable_tmpfiles = True
#
# This also includes the reboot components for njeji written by gwaugh
# you need to the a --tags=prepare then --tags=reboot
# this ensures all the njeji specific things are shutdown correctly before rebooting.


- hosts: njeji-patching-6
  gather_facts: False
  remote_user: lbernauer
  become: yes
  tasks:
    - name: get uptime
      shell:  uptime
      become: yes
      register: result
      tags: uptime
    - debug:
        var: result
      tags: uptime
    - name: Shut down crond
      shell: /sbin/service crond stop
      ignore_errors: yes
      tags: prepare
    - name: Shut down splunk
      shell: /sbin/service splunk stop
      ignore_errors: yes
      tags: prepare
    - name: Shut down oem agent
      shell: /sbin/service gcstartup stop
      ignore_errors: yes
      tags: prepare
    - name: Touch /forcefsck
      shell: touch /forcefsck
      tags: prepare
    - name: Kill all processes with open NFS files
      shell: lsof -N | awk '{print $2}'| grep -v PID | sort | uniq | xargs kill -9
      ignore_errors: yes
      tags: prepare
    - name: Sleep and reboot
      shell: sleep 30 && /sbin/reboot
      tags: reboot
    - name: mkdir mp3
      shell: mkdir /root/mp3
      tags: mp3_mkdir
    - name: Copy mp3
      shell: cp /home/lbernauer/agent64-linux-rhel6-6.7.6.7.3_ML.bin /root/mp3
      tags: mp3_cp
    - name: Install MP3
      shell: /root/mp3/agent64-linux-rhel6-6.7.6.7.3_ML.bin -silent
      tags: mp3_run
    - name: Verify MP3 1
      shell: su - sisips -c "/opt/Symantec/sdcssagent/IPS/bin/sisipsconfigtool -export"
      register: result
      tags: mp3_verify
    - debug:
        var: result
      tags: mp3_verify
    - name: Verify MP3 2
      shell: su - sisips -c "/opt/Symantec/sdcssagent/IPS/bin/sisipsconfigtool -t"
      register: result
      tags: mp3_verify2
    - debug:
        var: result
      tags: mp3_verify2
    - name: Change timezone
      timezone:
        name: Australia/Sydney
      tags: fix_time
    - name: Zabbix Restart
      shell: service zabbix-agent restart
      register: result
      tags: zabbix_restart
    - debug:
        var: result
      tags: zabbix_restart
