# Configure Elasticsearch nodes and do a rolling restart

- hosts: sundryhosts
  serial: 1

  tasks:
   - name: Remove old elasticsearch files
     shell: 'rm -f /etc/systemd/system/multi-user.target.wants/elasticsearch-es-01.service'

   - name: Remove CentOS repo files
     shell: 'rm -f /etc/yum.repos.d/CentOS*'

   - name: Do a 'yum clean all'
     shell: 'yum clean all'

   - name: Change /var/lib/puppet to mode 0751
     file:
       path: /var/lib/puppet
       mode: '0751'

   - name: Do a systemctl daemon-reload
     shell: 'systemctl daemon-reload'
      
   - name: Remove '--quiet' from elasticsearch service file
     lineinfile:
       path: /usr/lib/systemd/system/elasticsearch.service
       state: present
       backrefs: yes
       regexp: '^ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p \$\{PID_DIR\}/elasticsearch.pid --quiet$'
       line: 'ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid'

   - name: Configure JVM heap Xms setting
     lineinfile:
       path: /etc/elasticsearch/jvm.options
       state: present
       backrefs: yes
       regexp: '^-Xms1g$'
       line: '-Xms16g'

   - name: Configure JVM heap Xmx setting
     lineinfile:
       path: /etc/elasticsearch/jvm.options
       state: present
       backrefs: yes
       regexp: '^-Xmx1g$'
       line: '-Xmx16g'

   - name: Ensure elasticsearch service override directory exists
     file:
       path: /etc/systemd/system/elasticsearch.service.d
       state: directory
       owner: root
       group: root
       mode: 0755

   - name: Ensure elasticsearch service override file exists
     copy:
       src: files/elasticsearch.override.conf
       dest: /etc/systemd/system/elasticsearch.service.d/override.conf
       owner: root
       group: root
       mode: 0644

   - name: Configure elasticsearch.yml file
     template:
       src: templates/elasticsearch.yml.j2
       dest: /etc/elasticsearch/elasticsearch.yml
       owner: root
       group: elasticsearch
       mode: 0660

   - name: Run 'systemctl daemon-reload'
     shell: 'systemctl daemon-reload'

   - name: disable cluster routing
     shell: "curl -XPUT -H 'Content-Type: application/json' {{ private_ip }}:9200/_cluster/settings -d '{\"transient\" : {\"cluster.routing.allocation.enable\" : \"none\" }}'"
     register: result
     until: result.stdout.find('"acknowledged"') != -1
     retries: 200
     delay: 3
     changed_when: result.stdout.find('"acknowledged":true') != -1

   - name: Restart and enable elasticsearch service
     service:
       name: elasticsearch
       enabled: yes
       state: restarted

   - name: wait for node to restart
     shell: "curl -I -s -m 10 {{ private_ip }}:9200 | head -n 1"
     register: result
     until: result.stdout == "HTTP/1.1 200 OK"
     retries: 200
     delay: 3

   - name: enable cluster routing
     shell: "curl -XPUT -H 'Content-Type: application/json' {{ private_ip }}:9200/_cluster/settings -d '{\"transient\" : {\"cluster.routing.allocation.enable\" : \"all\" }}'"
     register: result
     until: result.stdout.find('"acknowledged"') != -1
     retries: 200
     delay: 3
     changed_when: result.stdout.find('"acknowledged":true') != -1

   - name: wait for cluster to stabilize
     shell: "curl -s -m 10 {{ private_ip }}:9200/_cat/health | cut -d ' ' -f 4"
     register: result
     until: result.stdout.find("green") != -1
     retries: 200
     delay: 30

