# Replace the puppet certificate on puppet agents
# This was used in November/December 2018 to renew the puppet agent certificate
# after the CA certificate was renewed. The old CA certificate's issuer was
# different to the new CA certificate's issuer, so the test for whether an agent
# needed a new certificate could be made by testing the issuer of the existing cert.

 ###- hosts: govDC-unanderra-aesg-dev:govDC-unanderra-aesg-dr:govDC-unanderra-aesg-qa:govDC-silverwater-aesg-prod
- hosts: govDC-silverwater-aesg-prod

  vars:
     puppet_status: ""

  tasks:
   - name: Initialise 'started' variable
     set_fact:
       started: false

   - name: Check whether puppet certificate is correct
     command: openssl x509 -in "/var/lib/puppet/ssl/certs/{{ ansible_fqdn }}.pem" -noout -issuer
     register: cert_issuer

   - block:

       - name: Determine whether puppet service is running
         shell: service puppet status
         ignore_errors: true
         register: puppet_status

       - name: Save state of puppet service
         set_fact:
           started: true
         when: '"running" in puppet_status.stdout'

       - debug:
           msg: "started is: {{started}}"

       - name: Stop puppet service if it is running
         service:
           name: puppet
           state: stopped
         ignore_errors: yes
         when: started

       - name: Copy puppet.conf file to /etc/puppet
         copy:
           src: files/generic-puppet.conf
           dest: /etc/puppet/puppet.conf
           owner: root
           group: root
           mode: 0644

       - name: Remove puppet SSL .old directory if it exists
         shell: rm -rf /var/lib/puppet/ssl.old
         ignore_errors: yes

       - name: Rename puppet SSL directory to .old
         command: mv /var/lib/puppet/ssl /var/lib/puppet/ssl.old creates=/var/lib/puppet/ssl.old removes=/var/lib/puppet/ssl

       - name: Run puppet in noop mode to generate CSR
         shell: puppet agent -t --noop
         ignore_errors: yes

       - name: Start puppet service if it was running
         service:
           name: puppet
           state: started
         when: started

       - name: Remove puppet SSL .old directory again
         shell: rm -rf /var/lib/puppet/ssl.old

     when: '"master.lab.com" not in cert_issuer.stdout'
