# - name: Wait for the server to finish rebooting
#   sudo: no
#   local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300
#   tags: reboot
- name: Copy Servers Spec Test to server
  copy: src="/home/njejimyv/goss/gossfiles/{{ansible_hostname}}.goss.json" dest=/tmp/ owner=root group=root mode=0644
  tags: execute_goss
- name: Copy package list spec test to server
  copy: src=/home/njejimyv/goss/gossfiles/packages.goss.json dest=/tmp/ owner=root group=root mode=0644
  tags: execute_goss
- name: Go ServerSpec Execute
  shell: /usr/local/bin/goss -g "/tmp/{{ansible_hostname}}.goss.json" validate --format documentation > "/tmp/{{ansible_hostname}}.txt"
  ignore_errors: yes
  tags: execute_goss
- name: Remove previous reports
  local_action: command rm -rf ~/.ansible/goss/{{inventory_hostname}}/
  sudo: no
  tags: execute_goss
- name: Fetch goss report
  fetch: src=/tmp/{{ansible_hostname}}.txt dest=~/.ansible/goss/
  tags:  execute_goss
 


- name: Unmount legacy NFS paths - npt1qzone 
  shell: umount /npt1qzone
  ignore_errors: yes
  tags: unmount_legacy_mounts_nonp
- name: Unmount legacy NFS paths - npt2qzone 
  shell: umount /npt2qzone
  ignore_errors: yes
  tags: unmount_legacy_mounts_nonp
- name: Unmount legacy NFS paths - pdt1qzone 
  shell: umount /pdt1qzone
  ignore_errors: yes
  tags: unmount_legacy_mounts_prod
- name: Unmount legacy NFS paths - pdt2qzone 
  shell: umount /pdt2qzone
  ignore_errors: yes
  tags: unmount_legacy_mounts_prod
- name: Unmount legacy NFS paths - pft1qzone 
  shell: umount /pft1qzone
  ignore_errors: yes
  tags: unmount_legacy_mounts_nonp
- name: Unmount legacy NFS paths - pft2qzone 
  shell: umount /pft2qzone
  ignore_errors: yes
  tags: unmount_legacy_mounts_nonp
- name: Unmount legacy NFS paths - sdt1qzone 
  shell: umount /sdt1qzone
  ignore_errors: yes
  tags: unmount_legacy_mounts_nonp
- name: Unmount legacy NFS paths - sdt2qzone 
  shell: umount /sdt2qzone
  ignore_errors: yes
  tags: unmount_legacy_mounts_nonp
- name: Unmount legacy NFS paths - svt1qzone 
  shell: umount /svt1qzone
  ignore_errors: yes
  tags: unmount_legacy_mounts_nonp
- name: Unmount legacy NFS paths - svt2qzone 
  shell: umount /svt2qzone
  ignore_errors: yes
  tags: unmount_legacy_mounts_nonp



- name: Removing legacy NFS paths - npt1qzone 
  shell: sed -i '/common_npt1qzone/d' /etc/fstab
  ignore_errors: yes
  tags: remove_legacy_mounts_nonp
- name: Removing legacy NFS paths - npt2qzone 
  shell: sed -i '/common_npt2qzone/d' /etc/fstab
  ignore_errors: yes
  tags: remove_legacy_mounts_nonp
- name: Removing legacy NFS paths - pdt1qzone 
  shell: sed -i '/common_pdt1qzone/d' /etc/fstab
  ignore_errors: yes
  tags: remove_legacy_mounts_prod
- name: Removing legacy NFS paths - pdt2qzone 
  shell: sed -i '/common_pdt2qzone/d' /etc/fstab
  ignore_errors: yes
  tags: remove_legacy_mounts_prod
- name: Removing legacy NFS paths - pft1qzone 
  shell: sed -i '/common_pft1qzone/d' /etc/fstab
  ignore_errors: yes
  tags: remove_legacy_mounts_nonp
- name: Removing legacy NFS paths - pft2qzone 
  shell: sed -i '/common_pft2qzone/d' /etc/fstab
  ignore_errors: yes
  tags: remove_legacy_mounts_nonp
- name: Removing legacy NFS paths - sdt1qzone 
  shell: sed -i '/common_sdt1qzone/d' /etc/fstab
  ignore_errors: yes
  tags: remove_legacy_mounts_nonp
- name: Removing legacy NFS paths - sdt2qzone 
  shell: sed -i '/common_sdt2qzone/d' /etc/fstab
  ignore_errors: yes
  tags: remove_legacy_mounts_nonp
- name: Removing legacy NFS paths - svt1qzone 
  shell: sed -i '/common_svt1qzone/d' /etc/fstab
  ignore_errors: yes
  tags: remove_legacy_mounts_nonp
- name: Removing legacy NFS paths - svt2qzone 
  shell: sed -i '/common_svt2qzone/d' /etc/fstab
  ignore_errors: yes
  tags: remove_legacy_mounts_nonp
