# Install and configure elasticsearch for graylog
- name: Install required packages
  yum:
      state: present
      name: "{{ item }}"
      disable_gpg_check: yes
  with_items:
      - elasticsearch
      - java-1.8.0-openjdk-headless
      - iptables-services
  tags: elasticsearch

- name: Create elasticsearch config file
  template:
      src: templates/graylog-elasticsearch.yml.j2
      dest: /etc/elasticsearch/elasticsearch.yml
      owner: root
      group: elasticsearch
      mode: 0660
  tags: elasticsearch

- name: Create elasticsearch jvm.options file
  template:
      src: templates/graylog-elasticsearch-jvmoptions.j2
      dest: /etc/elasticsearch/jvm.options
      owner: root
      group: elasticsearch
      mode: 0660
  tags: elasticsearch

- name: Create elasticsearch service extension directory
  file:
      path: /etc/systemd/system/elasticsearch.service.d
      state: directory
      owner: root
      group: root
      mode: 0755
  tags: elasticsearch

- name: Create elasticsearch service extension file
  copy:
      src: files/graylog-elasticsearch-service.conf
      dest: /etc/systemd/system/elasticsearch.service.d/elasticsearch.conf
      owner: root
      group: root
      mode: 0644
  tags: elasticsearch

- name: Configure iptables to only allow port 9200 connections from graylog servers
  iptables:
      chain: INPUT
      source: "{{ item }}"
      destination_port: 9200
      protocol: tcp
      jump: ACCEPT
  with_items: "{{ play_hosts }}"
  tags: elasticsearch
  when: "'azur' not in inventory_hostname"

- name: Configure iptables to only allow port 9300 connections from graylog servers
  iptables:
      chain: INPUT
      source: "{{ item }}"
      destination_port: 9300
      protocol: tcp
      jump: ACCEPT
  with_items: "{{ play_hosts }}"
  tags: elasticsearch
  when: "'azur' not in inventory_hostname"

- name: Configure iptables to deny port 9200 connections from any servers without allow rules
  iptables:
      chain: INPUT
      destination_port: 9200
      protocol: tcp
      jump: REJECT
  tags: elasticsearch
  when: "'azur' not in inventory_hostname"

- name: Configure iptables to deny port 9300 connections from any servers without allow rules
  iptables:
      chain: INPUT
      destination_port: 9300
      protocol: tcp
      jump: REJECT
  tags: elasticsearch
  when: "'azur' not in inventory_hostname"

- name: Save iptables rules
  command: /sbin/service iptables save
  tags: elasticsearch
  when: "'azur' not in inventory_hostname"

- name: Enable and start elasticsearch service through systemd
  systemd:
      daemon_reload: yes
      enabled: yes
      name: elasticsearch
      state: started
  tags: elasticsearch
