# Install and configure graylog-server package
- name: Install required graylog-server packages
  yum:
      state: present
      name: "{{ item }}"
      disable_gpg_check: yes
  with_items:
      - graylog-server
      - java-1.8.0-openjdk-headless
  tags: graylog-server

- name: Create graylog server.conf file
  template:
      src: templates/graylog-server.conf.j2
      dest: /etc/graylog/server/server.conf
      owner: root
      group: root
      mode: 0644
  tags: graylog-server

- name: Create graylog sysconfig file
  template:
      src: templates/graylog-server-sysconfig.j2
      dest: /etc/sysconfig/graylog-server
      owner: root
      group: root
      mode: 0644
  tags: graylog-server

- name: Enable and start graylog-server service through systemd
  systemd:
      daemon_reload: no
      enabled: yes
      name: graylog-server
      state: started
  tags: graylog-server

- name: Set file ownership and permissions of /etc/graylog directory recursively
  file:
      path: /etc/graylog
      owner: graylog
      group: root
      mode: "o-rwx"
      recurse: yes
      state: directory
  tags: graylog-server
