# Install and configure apache for cerebro
- name: Install required packages
  yum:
      state: present
      name: ['httpd', 'mod_ssl', 'mod_ldap']
  tags: httpd

# Note: the 'openssl_privatekey', 'openssl_csr' and 'openssl_certificate' modules don't work here as pyOpenSSL>=0.15 is required
- name: Create RSA private key and self-signed certificate for apache
  command: openssl req -x509 \
          -newkey rsa:4096 \
          -keyout /etc/pki/tls/private/cerebro-key.pem \
          -out /etc/pki/tls/certs/cerebro-cert.pem \
          -days 3650 \
          -nodes \
          -subj "/C=AU/ST=New South Wales/L=Sydney/O=NTT Com ICT Solutions Pty Ltd/OU=ESBU/CN={{ ansible_fqdn }}/emailAddress=root"
  args:
      creates: /etc/pki/tls/private/cerebro-key.pem
  tags: httpd

- name: Set RSA private key ownership and permissions
  file:
      path: /etc/pki/tls/private/cerebro-key.pem
      owner: root
      group: apache
      mode: 0440
  tags: httpd

- name: Set certificate ownership and permissions
  file:
      path: /etc/pki/tls/certs/cerebro-cert.pem
      owner: root
      group: root
      mode: 0644
  tags: httpd

- name: Add hosts file entries for local AD DCs
  lineinfile:
      path: /etc/hosts
      regexp: '.*{{ item.key }}$'
      line: "{{ item.value }} {{ item.key }}"
  loop: "{{ ad_dcs | dict2items }}"
  tags: httpd

- name: Create apache config file for cerebro 
  template:
      src: templates/httpd-cerebro.conf.j2
      dest: /etc/httpd/conf.d/cerebro.conf
      owner: root
      group: root
      mode: 0644
  tags: httpd

- name: Copy ESBU AD CA certificate to server
  copy:
      src: "{{ item }}"
      dest: "{{ httpd_ad_ca_cert_path }}"
      owner: root
      group: root
      mode: 0644
  with_items: "files/{{ httpd_ad_ca_cert_filename }}"
  tags: httpd

- name: Enable and start the apache service
  systemd:
      enabled: yes
      name: httpd
      state: restarted
      daemon_reload: yes
  tags: httpd
