---
- hosts: all 
  tasks:
   - name: Set sysctl HugePages
     sysctl: name=vm.nr_hugepages
             value={{ hugepages_val }}
             state=present
             reload=no
     become: true        
     tags: kernel, hugepages

   - name: Set sysctl Shared Mem Max
     sysctl: name=kernel.shmmax
             value={{ kshmmax_val }}
             state=present
             reload=yes
     become: true        
     tags: kernel

   - name: Set sysctl Shared Mem All
     sysctl: name=kernel.shmall
             value={{ kshmall_val }}
             state=present
             reload=yes
     become: true        
     tags: kernel

   - name: Create file for oracle limits
     file: path=/etc/security/limits.d/91_oracle.conf owner=root group=root mode=644 state=touch
     become: true        
     tags: kernel

   - name: Update limits.conf - oracle soft memlock
     pam_limits: dest=/etc/security/limits.d/91_oracle.conf 
                 domain=oracle 
                 limit_type=soft 
                 limit_item=memlock 
                 value={{ smemlock_val }}
     become: true        
     tags: kernel

   - name: Update limits.conf - oracle hard memlock
     pam_limits: dest=/etc/security/limits.d/91_oracle.conf 
                 comment="  Update after 256Gb -> 512Gb db node upgrade - CHG0042013"
                 domain=oracle 
                 limit_type=hard 
                 limit_item=memlock 
                 value={{ hmemlock_val }}
     become: true        
     tags: kernel

   - name: Update limits.conf - oemuser processes
     pam_limits: dest=/etc/security/limits.d/92_oemuser.conf
                 comment=" OEM Agent fails to start with OOM error"
                 domain=oemuser
                 limit_type=-
                 limit_item=nproc
                 value={{ nproc_oemuser_val }}
     become: true
     tags: kernel, oemagent

   - name : Set sysctl NUMA Balancing
     sysctl: name=kernel.numa_balancing
             value=0
             state=present
     become: true
     when: ansible_kernel == "4.1.12-94.7.1.el6uek.x86_64"
     tags: kernel

   - name : Setting Semaphores as per Customer requirement / Oracle Support
     sysctl: name=kernel.sem
             value={{ ksem }}
             state=present
             reload=yes
     tags: ksem
