# Role to build a graylog cluster out of N nodes
- import_tasks: graylog-prepare.yml
  when: "'azur' not in inventory_hostname"

- import_tasks: graylog-azure-prepare.yml
  when: "'azur' in inventory_hostname"

- import_tasks: graylog-elasticsearch.yml

- import_tasks: graylog-mongodb.yml

- import_tasks: graylog-server.yml

- import_tasks: graylog-cerebro.yml

- import_tasks: graylog-httpd.yml

- import_tasks: graylog-application.yml
  when: "'01' in inventory_hostname"

# Will revise post mongo replication and/or tape backup
# Backups to 02 for redundancy
- import_tasks: graylog-backup.yml
  when: "'log02' in inventory_hostname or 'log12' in inventory_hostname"
