# Name: njeji-node-reboots.yml
# Author: gwaugh
# Usage: Use 'prepare' tag to kill all processes with open NFS file handles... tries to shut things down nicely first, then nukes them if they are still running
#        Use 'reboot' tag to reboot nodes with 30 second sleep to avoid overwhelming the hypervisors and storage with work
# Could be made more ansible-compatible, e.g. use the 'service' module etc.
- hosts: njeji-sva
  remote_user: njejimyv
  become: yes
  tasks:
    - name: Shut down crond
      shell: /sbin/service crond stop
      ignore_errors: yes
      tags: prepare
    - name: Shut down splunk
      shell: /sbin/service splunk stop
      ignore_errors: yes
      tags: prepare
    - name: Shut down oem agent
      shell: /sbin/service gcstartup stop
      ignore_errors: yes
      tags: prepare
    - name: Touch /forcefsck
      shell: touch /forcefsck
      tags: prepare
    - name: Kill all processes with open NFS files
      shell: lsof -N | awk '{print $2}'| grep -v PID | sort | uniq | xargs kill -9
      ignore_errors: yes
      tags: prepare
    - name: Sleep and reboot
      shell: sleep 30 && /sbin/reboot
      tags: reboot
