---

- name: Stop ntpd
  service:
       name: ntpd
       state: stopped
  tags: sync_ntp

- name: Sync time to server
  shell:  "ntpdate {{ntp_server}}"
  tags: sync_ntp

- name: Start ntpd
  service:
       name: ntpd
       state: started
       enabled: yes
  tags: sync_ntp

#- name: Set timezone
#  shell: "/usr/sbin/ipa-client-install --uninstall --unattended; rm -rf /etc/krb5.keytab /etc/ipa; yum remove -y ipa*"
#  tags: deregister_ipa
