---
- name: Timestamp puppet log
  shell: echo -e "\n`date`:#############################################################################################\n\n" >> /tmp/puppet_agent.log
  tags:
       - execute_puppet_noop
       - execute_puppet
- name: Puppet NOOP Run
  shell: puppet agent -tv --tags 'users' --noop >> /tmp/puppet_agent.log
  tags:
       - execute_puppet_noop
- name: Execute puppet run
  shell: puppet agent -tv >> /tmp/puppet_agent.log 2>&1
  register: puppet_agent_result
  changed_when: puppet_agent_result.rc == 2
  failed_when: puppet_agent_result.rc != 2 and puppet_agent_result.rc != 0
  tags: execute_puppet
- name: Fetch puppet log
  fetch: src=/tmp/puppet_agent.log dest=~/.ansible
  tags:
       - execute_puppet_noop
       - execute_puppet
- name: Enable puppet
  service:
       name: puppet
       state: started
       enabled: yes
  tags: enable_puppet
- name: Force kill puppet
  shell: "pkill -9 puppet"
  tags:
        - force_restart_puppet
- name: Restart puppet
  service:
       name: puppet
       state: restarted
       enabled: yes
  tags: 
        - restart_puppet
        - force_restart_puppet
- name: Disable puppet
  service:
       name: puppet
       state: stopped
       enabled: no
  tags: disable_puppet
- name: Disable puppet listen
  shell: "sed -i 's/listen/#listen/' /etc/puppet/puppet.conf"
  tags: disable_puppet_listen
- name: Disable puppet ignore schedule
  shell: "sed -i 's/ignore/#ignore/' /etc/puppet/puppet.conf"
  tags: disable_puppet_ignore_schedule
- name: Point puppet to master
  shell: "sed -i 's/server = puppet.lab.com.au/server = master.lab.com/' /etc/puppet/puppet.conf"
  tags: point_puppet_to_globpuppet
