---
# Name: njeji-symantec-agent.yml
# Author: charris
# Usage: This playbook can be used to manage aspects of the Symantec Linux agents.  Each function for these agents should be added to this playbook
# which will make it easier to maintain in the future.
# please note that the dropping of privileges to the sisips user to control the agents was a real pain in the arse to get to work.
# also you may need to add the following directive to your asible.cfg file in the defaults section
# [defaults]
# allow_world_readable_tmpfiles = True
#
# This also includes the reboot components for njeji written by gwaugh
# you need to the a --tags=prepare then --tags=reboot  
# this ensures all the njeji specific things are shutdown correctly before rebooting. 


#- hosts: njeji-20180125
- hosts: njeji-20180129
#- hosts: ~njeji-ptf-(drp|dsm|hrd|hmr|oaa|oab|obi|oes|ohm|ohp|oid|oif|oim|opt|sol|wbc)
#- hosts: njeji-20180116
#- hosts: njeji-svp-sft
#- hosts: ~njeji-svp-(dsm|hdr|hmr|oaa|oab|ohm|obi|oes|oid|opt|wbc)
  gather_facts: False
  remote_user: njejimyv
  become: yes
  tasks:
    - name: get uptime
      shell:  uptime
      become: yes
      register: result
      tags: uptime
    - debug:
        var: result
      tags: uptime
    - name: test id
      shell:  su - sisips -c id
      become: yes
      become_user: root
      become_method:  su
      register: result
      tags: test
    - debug:
        var: result
      tags: test
    - name: enable symantec ipsagent 
      shell: su - sisips -c "/opt/Symantec/sdcssagent/IPS/sisipsconfig.sh -ipsstate on"
      become: yes
      become_user: root
      register: result
      tags: enable_ips_agent
    - debug:
        var: result
      tags: enable_ips_agent
    - name: disable symantec ipsagent 
      shell: su - sisips -c "/opt/Symantec/sdcssagent/IPS/sisipsconfig.sh -ipsstate off"
      become: yes
      become_user: root 
      register: result
      tags: disable_ips_agent
    - debug:
        var: result.stdout_lines
      tags: disable_ips_agent
    - name: Get ips agent status 
      shell: /etc/init.d/sisipsagent status
      register: result
      tags: status_ips_agent
    - debug:
        var: result.stdout_lines
      tags: status_ips_agent
    - name: Shut down crond
      shell: /sbin/service crond stop
      ignore_errors: yes
      tags: prepare
    - name: Shut down splunk
      shell: /sbin/service splunk stop
      ignore_errors: yes
      tags: prepare
    - name: Shut down oem agent
      shell: /sbin/service gcstartup stop
      ignore_errors: yes
      tags: prepare
    - name: Touch /forcefsck
      shell: touch /forcefsck
      tags: prepare
    - name: Kill all processes with open NFS files
      shell: lsof -N | awk '{print $2}'| grep -v PID | sort | uniq | xargs kill -9
      ignore_errors: yes
      tags: prepare
    - name: Sleep and reboot
      shell: sleep 30 && /sbin/reboot
      tags: reboot
