---
# Name: njeji-upgrade.yml
# Author: lbernauer
# Usage: This playbook is used to patch the NJeJI VMs which require the uninstalling of DCS first. Also require the removal of postfix and exim
# from the vms.
# This playbook was adapted from the njeji-symantec-agent.yaml that charris wrote as most of those commands are needed as reinstalling of agent
# is required at the end of the patching
# please note that the dropping of privileges to the sisips user to control the agents was a real pain in the arse to get to work.
# also you may need to add the following directive to your ansible.cfg file in the defaults section
# [defaults]
# allow_world_readable_tmpfiles = True
#
# This also includes the reboot components for njeji written by gwaugh
# you need to the a --tags=prepare then --tags=reboot  
# this ensures all the njeji specific things are shutdown correctly before rebooting. 


- hosts: ~njeji-patch-(6|7|8|9)
  gather_facts: False
  remote_user: njejimyv
  become: yes
  tasks:
    - name: get uptime
      shell:  uptime
      become: yes
      register: result
      tags: uptime
    - debug:
        var: result
      tags: uptime
    - name: test id
      shell:  su - sisips -c id
      become: yes
      become_user: root
      become_method:  su
      register: result
      tags: test
    - debug:
        var: result
      tags: test
    - name: enable symantec ipsagent 
      shell: su - sisips -c "/opt/Symantec/sdcssagent/IPS/sisipsconfig.sh -ipsstate on"
      become: yes
      become_user: root
      register: result
      tags: enable_ips_agent
    - debug:
        var: result
      tags: enable_ips_agent
    - name: disable symantec ipsagent 
      shell: su - sisips -c "/opt/Symantec/sdcssagent/IPS/sisipsconfig.sh -ipsstate off"
      become: yes
      become_user: root 
      register: result
      tags: disable_ips_agent
    - debug:
        var: result.stdout_lines
      tags: disable_ips_agent
    - name: Get ips agent status 
      shell: /etc/init.d/sisipsagent status
      register: result
      tags: status_ips_agent
    - debug:
        var: result.stdout_lines
      tags: status_ips_agent
    - name: Shut down crond
      shell: /sbin/service crond stop
      ignore_errors: yes
      tags: prepare
    - name: Shut down splunk
      shell: /sbin/service splunk stop
      ignore_errors: yes
      tags: prepare
    - name: Shut down oem agent
      shell: /sbin/service gcstartup stop
      ignore_errors: yes
      tags: prepare
    - name: Touch /forcefsck
      shell: touch /forcefsck
      tags: prepare
    - name: Kill all processes with open NFS files
      shell: lsof -N | awk '{print $2}'| grep -v PID | sort | uniq | xargs kill -9
      ignore_errors: yes
      tags: prepare
    - name: Sleep and reboot
      shell: sleep 30 && /sbin/reboot
      tags: reboot
    - name: Remove cache
      shell: rm -rf /var/cache/yum/*
      register: result
      tags: cache_remove
    - debug:
        var: result
      tags: cache_remove
    - name: Update vm
      shell: yum -y update
      register: result
      tags: vm_update
    - debug:
        var: result
      tags: vm_update
    - name: Remove repos
      shell: rm /etc/yum.repos.d/*.repo
      tags: repo_remove
    - name: Start sisid
      shell: /etc/init.d/sisidsagent start
      tags: symantec_start
    - name: Start sisip
      shell: /etc/init.d/sisipsagent start
      tags: symantec_start
    - name: Remove dcs
      shell: yum remove -y SYMCsdcss
      register: result
      tags: remove_dcs
    - debug:
        var: result
      tags: remove_dcs
    - name: Enable puppet
      shell: puppet agent --enable
      tags: run_puppet
    - name: Run puppet
      shell: puppet agent -tv
      tags: run_puppet
    - name: Start Postfix
      shell: service postfix start
      register: result
      tags: postfix_start
    - debug:
        var: result
      tags: postfix_start
    - name: Install Postfix
      shell: yum install -y postfix
      register: result
      tags: postfix_install
    - debug:
        var: result
      tags: postfix_install
    - name: Stop exim
      shell: service exim stop
      register: result
      tags: exim_stop
    - debug:
        var: result
      tags: exim_stop
    - name: Remove exim
      shell: rpm -e --nodeps "exim-4.90.1-3.el6.x86_64"
      register: result
      tags: exim_remove
    - debug:
        var: result
      tags: exim_remove
    - name: Remove mysql libs1
      shell: rpm -e --nodeps mysql-community-libs-compat-5.6.23-2.el6.x86_64
      register: result
      tags: mysql_remove
    - debug:
        var: result
      tags: mysql_remove
    - name: Remove mysql libs2
      shell: rpm -e --nodeps mysql-community-common-5.6.23-2.el6.x86_64
      register: result
      tags: mysql_remove
    - debug:
        var: result
      tags: mysql_remove
    - name: Remove mysql libs3
      shell: rpm -e --nodeps mysql-community-libs-5.6.23-2.el6.x86_64
      register: result
      tags: mysql_remove
    - debug:
        var: result
      tags: mysql_remove
    - name: Install mysql libs
      shell: yum install -y mysql-libs
      register: result
      tags: mysql_install
    - debug:
        var: result
      tags: mysql_install
    - name: Restart Postfix
      shell: service postfix restart
      register: result
      tags: postfix_restart
    - debug:
        var: result
      tags: postfix_restart
