- name: Uptime of server in seconds
  command: "cat /proc/uptime | awk '{print $1}'"
  register: uptime_secs
  tags: uptime_secs
- name: Uptime of server
  command: "uptime"
  register: uptime
  tags: uptime
- debug: msg="{{ uptime.stdout }}"
  tags: uptime
