Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.50.4",
     auto_config: false

  config.vm.network "private_network", ip: "192.168.50.5",
     auto_config: false

  config.vm.provider "virtualbox" do |vb|
   vb.name = "patchtest"
   vb.cpus = "1"
   vb.memory = "1024"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
  end
end
