---

- name: Create VMWare Snapshot
  connection: local
  gather_facts: false

  vars:

    aesg_prod_silw: 'Inventories/production/vars/aesg_production_vmware_vms.yml'

  vars_prompt:

    - name: "vcenter_username"
      prompt: "Enter vcenter username"
      private: no

    - name: "vcenter_password"
      prompt: "Enter vcenter password"
      private: yes

    - name: "vcenter_snapshot_state"
      prompt: "Enter snapshot state (present, absent or remove_all)"

    - name: "vcenter_customer_variable_file"
      prompt: "Enter customer, environment and location (e.g: aesg_prod_silw)"

  vars_files:

    - "{{ vcenter_customer_variable_file }}"


  pre_tasks:

    - name: Install required dependencies for VMWare vCenter
      pip:
        name: PyVmomi
        state: present
      become: True


  tasks:

    - name: Check vmware facts
      vmware_vm_facts:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false
      register: vmfacts

    - name: Manage vmware snapshot
      vmware_guest_snapshot:
        datacenter: "{{ vcenter_datacenter }}"
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        uuid: "{{ vmfacts['virtual_machines']['%s'| format(item)]['uuid'] }}"
        validate_certs: false
        snapshot_name: "{{ vcenter_snapshot_name }}"
        description: "{{ vcenter_snapshot_description }}"
        state: "{{ vmware_snapshot_state }}"
      loop: "{{ vmware_vm_guests | flatten(levels=1) }}"
