---
- name: Add group "zookeeper"
  group: name={{ zookeeper_group }} system=yes

- name: Add user "zookeeper"
  user: name={{ zookeeper_group }} group={{ zookeeper_group }} home={{ zookeeper_data_dir }} shell=/sbin/nologin system=yes

- name: Download the tarball
  get_url: url=http://{{ apache_mirror }}/zookeeper/zookeeper-{{ zookeeper_version }}/zookeeper-{{ zookeeper_version }}.tar.gz dest={{ zookeeper_root_dir }}/zookeeper-{{ zookeeper_version }}.tar.gz

- name: Extract the tarball
  unarchive: src={{ zookeeper_root_dir }}/zookeeper-{{ zookeeper_version }}.tar.gz dest={{ zookeeper_root_dir }}/ copy=no creates={{ zookeeper_root_dir }}/zookeeper-{{ zookeeper_version }}

- name: Symlink install directory
  file: src={{ zookeeper_root_dir }}/zookeeper-{{ zookeeper_version }} path={{ zookeeper_root_dir }}/zookeeper state=link

- name: Set permissions to Zookeeper folder
  file: path={{ zookeeper_root_dir }}/zookeeper/ owner=root group=root recurse=yes

- name: Create Zookeeper data directory
  file: path={{ zookeeper_data_dir }} state=directory owner={{ zookeeper_user }} group={{ zookeeper_group }}

- name: Create Zookeeper log directory
  file: path={{ zookeeper_log_dir }} state=directory owner={{ zookeeper_user }} group={{ zookeeper_group }}

- name: Create Zookeeper conf directory
  file: path={{ zookeeper_conf_dir }} state=directory owner=root group=root mode=755

- name: Install Zookeeper init script
  template: src=zookeeper.j2 dest=/etc/systemd/system/zookeeper.service mode=0644
  notify: Reload systemd

- meta: flush_handlers

- name: Configure Zookeeper server
  template: src=zoo.cfg.j2 dest="{{zookeeper_conf_dir}}/zoo.cfg"
  notify: Restart zookeeper

- name: Configure myid
  template: src=myid.j2 dest="{{ zookeeper_data_dir }}/myid"
  notify: Restart zookeeper

- name: Upload log4j config
  copy: src=log4j.properties dest="{{ zookeeper_conf_dir }}/log4j.properties" owner=root group=root mode=644
  notify: Restart zookeeper

- meta: flush_handlers

- name: Make sure Zookeeper is running
  service: name=zookeeper enabled=yes state=started

- name: Add Zookeeper binaries to PATH
  template: src=zookeeper.sh.j2 dest=/etc/profile.d/zookeeper.sh owner=root group=root mode=644
