---
language: ruby
cache: bundler
sudo: required
services:
  - docker
script:
  - bundle exec rake validate lint beaker
rvm:
  - 2.1.6
env:
  - BEAKER_set="default"
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes
