class common::rsyslog::client (
    $log_server                    = "",
    $remote_servers                = false,
    $log_remote                    = false,
    $custom_config                 = undef,
    $remote_type                   = 'tcp',
    $rebind_every                  = false,
    $action_queue_size             = false,
    $action_queue_discard_mark     = false,
    $action_queue_discard_severity = false,
    $spool_timeoutenqueue          = false,
    $action_queue_low_water_mark   = false,
    $action_queue_high_water_mark  = false,
    $actionfiletemplate            = false,
    $remote_forward_format         = 'RSYSLOG_ForwardFormat',
    $log_templates                 = false,
    $enable_pstats                 = false,
    $pstat_interval                = 300,
    $pstat_facility                = 5,
    $pstat_severity                = 6,
    $port                          = '514',
) {
    $additional_snippets = hiera_hash('common::rsyslog::client::additional_snippets', {})

    class { '::rsyslog::client':
      log_remote                    => $log_remote,
      remote_type                   => $remote_type,
      rebind_every                  => $rebind_every,
      action_queue_size             => $action_queue_size,
      action_queue_discard_mark     => $action_queue_discard_mark,
      action_queue_discard_severity => $action_queue_discard_severity,
      spool_timeoutenqueue          => $spool_timeoutenqueue,
      action_queue_low_water_mark   => $action_queue_low_water_mark,
      action_queue_high_water_mark  => $action_queue_high_water_mark,
      log_local                     => true,
      log_auth_local                => true,
      custom_config                 => $custom_config,
      server                        => $log_server,
      remote_servers                => $remote_servers,
      port                          => $port,
      actionfiletemplate            => $actionfiletemplate,
      remote_forward_format         => $remote_forward_format,
      log_templates                 => $log_templates,
      enable_pstats                 => $enable_pstats,
      pstat_interval                => $pstat_interval,
      pstat_facility                => $pstat_facility,
      pstat_severity                => $pstat_severity,
      additional_snippets           => $additional_snippets,
    }
}
